### PR TITLE
add @Security decorator using passport

### PR DESCRIPTION
**Pull request by d0whc3r**
Examples and tests using passport-jwt

### CODE REVIEW

**Comment by nkimaina** [comment]
Is this being merged?

**Comment by d0whc3r** [comment]
> Also interested: is it being merged?

Yes it was merged. Documentation is in README
https://github.com/thiagobustamante/typescript-rest#security-decorator

You could check for tests for more detailed implementation.

I don't know if it is published to npm...

**Comment by d0whc3r** [comment]
No it is not published to npm, you need to import source code from github if you want to use `@Security` decorator

**Comment by mautematico** [comment]
You're right, it was merged!

I'm going to use it :) Thank you @d0whc3r

**Comment by garyevari** [comment]
Anyone able to comment on when a new version might be published to include this change?

**Comment by garyevari** [comment]
@d0whc3r using this code, how would you go about setting session to false on each of the endpoints so that passport doesn't complain about being unable to serialize/deserialize the user?

**Comment by garyevari** [comment]
Figured it out - will make a PR to config that

**Pull request merged**
